# Need these for a more recent CMake on Linux
sudo: required
dist: trusty

os:
  - linux
  - osx

language: cpp

before_script:
  - mkdir build
  - cd build
  - cmake --config Release ..

script:
  - cmake --build . --config Release

after_script:
  - cmake --build . --target test --config Release
